
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May 22 2026 10:12:04 IST (May 22 2026 04:42:04 UTC)

// Verification Directory fv/sync_fifo 

module sync_fifo(clk, rst_n, wr_en, rd_en, data_in, data_out, full,
     empty);
  input clk, rst_n, wr_en, rd_en;
  input [7:0] data_in;
  output [7:0] data_out;
  output full, empty;
  wire clk, rst_n, wr_en, rd_en;
  wire [7:0] data_in;
  wire [7:0] data_out;
  wire full, empty;
  wire [4:0] count;
  wire [7:0] \fifo_ram[15] ;
  wire [7:0] \fifo_ram[9] ;
  wire [7:0] \fifo_ram[10] ;
  wire [7:0] \fifo_ram[8] ;
  wire [7:0] \fifo_ram[12] ;
  wire [7:0] \fifo_ram[14] ;
  wire [7:0] \fifo_ram[13] ;
  wire [7:0] \fifo_ram[11] ;
  wire [7:0] \fifo_ram[6] ;
  wire [7:0] \fifo_ram[5] ;
  wire [7:0] \fifo_ram[2] ;
  wire [7:0] \fifo_ram[1] ;
  wire [7:0] \fifo_ram[4] ;
  wire [7:0] \fifo_ram[0] ;
  wire [7:0] \fifo_ram[3] ;
  wire [7:0] \fifo_ram[7] ;
  wire [3:0] w_ptr;
  wire [3:0] r_ptr;
  wire n_3, n_4, n_5, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_16, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_205, n_206, n_207;
  wire n_208;
  DFFRHQX1 \data_out_reg[0] (.RN (rst_n), .CK (clk), .D (n_197), .Q
       (data_out[0]));
  DFFRHQX1 \data_out_reg[2] (.RN (rst_n), .CK (clk), .D (n_195), .Q
       (data_out[2]));
  DFFRHQX1 \data_out_reg[3] (.RN (rst_n), .CK (clk), .D (n_198), .Q
       (data_out[3]));
  DFFRHQX1 \data_out_reg[7] (.RN (rst_n), .CK (clk), .D (n_196), .Q
       (data_out[7]));
  DFFRHQX1 \data_out_reg[5] (.RN (rst_n), .CK (clk), .D (n_200), .Q
       (data_out[5]));
  DFFRHQX1 \data_out_reg[6] (.RN (rst_n), .CK (clk), .D (n_194), .Q
       (data_out[6]));
  DFFRHQX1 \data_out_reg[4] (.RN (rst_n), .CK (clk), .D (n_193), .Q
       (data_out[4]));
  DFFRHQX1 \data_out_reg[1] (.RN (rst_n), .CK (clk), .D (n_199), .Q
       (data_out[1]));
  NAND4XL g5309__2398(.A (n_95), .B (n_136), .C (n_169), .D (n_189), .Y
       (n_200));
  NAND4XL g5308__5107(.A (n_116), .B (n_100), .C (n_172), .D (n_186),
       .Y (n_199));
  NAND4XL g5302__6260(.A (n_132), .B (n_129), .C (n_146), .D (n_184),
       .Y (n_198));
  NAND4XL g5304__4319(.A (n_115), .B (n_105), .C (n_167), .D (n_188),
       .Y (n_197));
  NAND4XL g5312__8428(.A (n_107), .B (n_97), .C (n_147), .D (n_185), .Y
       (n_196));
  NAND4XL g5311__5526(.A (n_102), .B (n_134), .C (n_164), .D (n_192),
       .Y (n_195));
  NAND4XL g5310__6783(.A (n_133), .B (n_104), .C (n_168), .D (n_191),
       .Y (n_194));
  NAND4XL g5305__3680(.A (n_119), .B (n_118), .C (n_173), .D (n_187),
       .Y (n_193));
  DFFRHQX1 \count_reg[4] (.RN (rst_n), .CK (clk), .D (n_176), .Q
       (count[4]));
  AOI21XL g5321__1617(.A0 (\fifo_ram[15] [2]), .A1 (n_190), .B0
       (n_162), .Y (n_192));
  AOI21XL g5320__2802(.A0 (\fifo_ram[15] [6]), .A1 (n_190), .B0
       (n_161), .Y (n_191));
  AOI21XL g5318__1705(.A0 (\fifo_ram[15] [5]), .A1 (n_190), .B0
       (n_159), .Y (n_189));
  AOI21XL g5322__5122(.A0 (\fifo_ram[15] [0]), .A1 (n_190), .B0
       (n_174), .Y (n_188));
  AOI21XL g5314__8246(.A0 (\fifo_ram[15] [4]), .A1 (n_190), .B0
       (n_156), .Y (n_187));
  AOI21XL g5317__7098(.A0 (\fifo_ram[15] [1]), .A1 (n_190), .B0
       (n_158), .Y (n_186));
  AOI21XL g5323__6131(.A0 (\fifo_ram[15] [7]), .A1 (n_190), .B0
       (n_163), .Y (n_185));
  AOI21XL g5315__1881(.A0 (\fifo_ram[15] [3]), .A1 (n_190), .B0
       (n_155), .Y (n_184));
  DFFRHQX1 \count_reg[1] (.RN (rst_n), .CK (clk), .D (n_157), .Q
       (count[1]));
  EDFFHQX1 \fifo_ram_reg[9][4] (.CK (clk), .D (data_in[4]), .E (n_181),
       .Q (\fifo_ram[9] [4]));
  EDFFHQX1 \fifo_ram_reg[10][0] (.CK (clk), .D (data_in[0]), .E
       (n_183), .Q (\fifo_ram[10] [0]));
  EDFFHQX1 \fifo_ram_reg[10][6] (.CK (clk), .D (data_in[6]), .E
       (n_183), .Q (\fifo_ram[10] [6]));
  EDFFHQX1 \fifo_ram_reg[8][1] (.CK (clk), .D (data_in[1]), .E (n_182),
       .Q (\fifo_ram[8] [1]));
  EDFFHQX1 \fifo_ram_reg[8][2] (.CK (clk), .D (data_in[2]), .E (n_182),
       .Q (\fifo_ram[8] [2]));
  EDFFHQX1 \fifo_ram_reg[8][3] (.CK (clk), .D (data_in[3]), .E (n_182),
       .Q (\fifo_ram[8] [3]));
  EDFFHQX1 \fifo_ram_reg[8][4] (.CK (clk), .D (data_in[4]), .E (n_182),
       .Q (\fifo_ram[8] [4]));
  EDFFHQX1 \fifo_ram_reg[8][5] (.CK (clk), .D (data_in[5]), .E (n_182),
       .Q (\fifo_ram[8] [5]));
  EDFFHQX1 \fifo_ram_reg[8][6] (.CK (clk), .D (data_in[6]), .E (n_182),
       .Q (\fifo_ram[8] [6]));
  EDFFHQX1 \fifo_ram_reg[8][7] (.CK (clk), .D (data_in[7]), .E (n_182),
       .Q (\fifo_ram[8] [7]));
  EDFFHQX1 \fifo_ram_reg[9][0] (.CK (clk), .D (data_in[0]), .E (n_181),
       .Q (\fifo_ram[9] [0]));
  EDFFHQX1 \fifo_ram_reg[9][1] (.CK (clk), .D (data_in[1]), .E (n_181),
       .Q (\fifo_ram[9] [1]));
  EDFFHQX1 \fifo_ram_reg[9][2] (.CK (clk), .D (data_in[2]), .E (n_181),
       .Q (\fifo_ram[9] [2]));
  EDFFHQX1 \fifo_ram_reg[9][3] (.CK (clk), .D (data_in[3]), .E (n_181),
       .Q (\fifo_ram[9] [3]));
  OAI21XL g5303__5115(.A0 (n_111), .A1 (n_140), .B0 (n_112), .Y
       (n_180));
  EDFFHQX1 \fifo_ram_reg[9][5] (.CK (clk), .D (data_in[5]), .E (n_181),
       .Q (\fifo_ram[9] [5]));
  EDFFHQX1 \fifo_ram_reg[9][6] (.CK (clk), .D (data_in[6]), .E (n_181),
       .Q (\fifo_ram[9] [6]));
  EDFFHQX1 \fifo_ram_reg[9][7] (.CK (clk), .D (data_in[7]), .E (n_181),
       .Q (\fifo_ram[9] [7]));
  EDFFHQX1 \fifo_ram_reg[12][0] (.CK (clk), .D (data_in[0]), .E
       (n_179), .Q (\fifo_ram[12] [0]));
  EDFFHQX1 \fifo_ram_reg[14][5] (.CK (clk), .D (data_in[5]), .E
       (n_177), .Q (\fifo_ram[14] [5]));
  EDFFHQX1 \fifo_ram_reg[12][1] (.CK (clk), .D (data_in[1]), .E
       (n_179), .Q (\fifo_ram[12] [1]));
  EDFFHQX1 \fifo_ram_reg[12][2] (.CK (clk), .D (data_in[2]), .E
       (n_179), .Q (\fifo_ram[12] [2]));
  EDFFHQX1 \fifo_ram_reg[12][3] (.CK (clk), .D (data_in[3]), .E
       (n_179), .Q (\fifo_ram[12] [3]));
  EDFFHQX1 \fifo_ram_reg[12][4] (.CK (clk), .D (data_in[4]), .E
       (n_179), .Q (\fifo_ram[12] [4]));
  EDFFHQX1 \fifo_ram_reg[12][5] (.CK (clk), .D (data_in[5]), .E
       (n_179), .Q (\fifo_ram[12] [5]));
  EDFFHQX1 \fifo_ram_reg[12][6] (.CK (clk), .D (data_in[6]), .E
       (n_179), .Q (\fifo_ram[12] [6]));
  EDFFHQX1 \fifo_ram_reg[12][7] (.CK (clk), .D (data_in[7]), .E
       (n_179), .Q (\fifo_ram[12] [7]));
  EDFFHQX1 \fifo_ram_reg[13][6] (.CK (clk), .D (data_in[6]), .E
       (n_178), .Q (\fifo_ram[13] [6]));
  EDFFHQX1 \fifo_ram_reg[11][7] (.CK (clk), .D (data_in[7]), .E
       (n_175), .Q (\fifo_ram[11] [7]));
  EDFFHQX1 \fifo_ram_reg[10][2] (.CK (clk), .D (data_in[2]), .E
       (n_183), .Q (\fifo_ram[10] [2]));
  EDFFHQX1 \fifo_ram_reg[10][3] (.CK (clk), .D (data_in[3]), .E
       (n_183), .Q (\fifo_ram[10] [3]));
  EDFFHQX1 \fifo_ram_reg[10][4] (.CK (clk), .D (data_in[4]), .E
       (n_183), .Q (\fifo_ram[10] [4]));
  EDFFHQX1 \fifo_ram_reg[10][5] (.CK (clk), .D (data_in[5]), .E
       (n_183), .Q (\fifo_ram[10] [5]));
  EDFFHQX1 \fifo_ram_reg[8][0] (.CK (clk), .D (data_in[0]), .E (n_182),
       .Q (\fifo_ram[8] [0]));
  EDFFHQX1 \fifo_ram_reg[10][7] (.CK (clk), .D (data_in[7]), .E
       (n_183), .Q (\fifo_ram[10] [7]));
  EDFFHQX1 \fifo_ram_reg[13][0] (.CK (clk), .D (data_in[0]), .E
       (n_178), .Q (\fifo_ram[13] [0]));
  EDFFHQX1 \fifo_ram_reg[13][1] (.CK (clk), .D (data_in[1]), .E
       (n_178), .Q (\fifo_ram[13] [1]));
  EDFFHQX1 \fifo_ram_reg[13][2] (.CK (clk), .D (data_in[2]), .E
       (n_178), .Q (\fifo_ram[13] [2]));
  EDFFHQX1 \fifo_ram_reg[13][3] (.CK (clk), .D (data_in[3]), .E
       (n_178), .Q (\fifo_ram[13] [3]));
  EDFFHQX1 \fifo_ram_reg[13][4] (.CK (clk), .D (data_in[4]), .E
       (n_178), .Q (\fifo_ram[13] [4]));
  EDFFHQX1 \fifo_ram_reg[13][5] (.CK (clk), .D (data_in[5]), .E
       (n_178), .Q (\fifo_ram[13] [5]));
  EDFFHQX1 \fifo_ram_reg[13][7] (.CK (clk), .D (data_in[7]), .E
       (n_178), .Q (\fifo_ram[13] [7]));
  EDFFHQX1 \fifo_ram_reg[14][7] (.CK (clk), .D (data_in[7]), .E
       (n_177), .Q (\fifo_ram[14] [7]));
  EDFFHQX1 \fifo_ram_reg[14][0] (.CK (clk), .D (data_in[0]), .E
       (n_177), .Q (\fifo_ram[14] [0]));
  EDFFHQX1 \fifo_ram_reg[14][1] (.CK (clk), .D (data_in[1]), .E
       (n_177), .Q (\fifo_ram[14] [1]));
  EDFFHQX1 \fifo_ram_reg[14][2] (.CK (clk), .D (data_in[2]), .E
       (n_177), .Q (\fifo_ram[14] [2]));
  EDFFHQX1 \fifo_ram_reg[14][3] (.CK (clk), .D (data_in[3]), .E
       (n_177), .Q (\fifo_ram[14] [3]));
  EDFFHQX1 \fifo_ram_reg[14][4] (.CK (clk), .D (data_in[4]), .E
       (n_177), .Q (\fifo_ram[14] [4]));
  EDFFHQX1 \fifo_ram_reg[14][6] (.CK (clk), .D (data_in[6]), .E
       (n_177), .Q (\fifo_ram[14] [6]));
  OAI21XL g5313__7482(.A0 (count[4]), .A1 (n_143), .B0 (n_144), .Y
       (n_176));
  EDFFHQX1 \fifo_ram_reg[11][0] (.CK (clk), .D (data_in[0]), .E
       (n_175), .Q (\fifo_ram[11] [0]));
  EDFFHQX1 \fifo_ram_reg[11][1] (.CK (clk), .D (data_in[1]), .E
       (n_175), .Q (\fifo_ram[11] [1]));
  EDFFHQX1 \fifo_ram_reg[11][2] (.CK (clk), .D (data_in[2]), .E
       (n_175), .Q (\fifo_ram[11] [2]));
  EDFFHQX1 \fifo_ram_reg[11][3] (.CK (clk), .D (data_in[3]), .E
       (n_175), .Q (\fifo_ram[11] [3]));
  EDFFHQX1 \fifo_ram_reg[11][4] (.CK (clk), .D (data_in[4]), .E
       (n_175), .Q (\fifo_ram[11] [4]));
  EDFFHQX1 \fifo_ram_reg[11][5] (.CK (clk), .D (data_in[5]), .E
       (n_175), .Q (\fifo_ram[11] [5]));
  EDFFHQX1 \fifo_ram_reg[11][6] (.CK (clk), .D (data_in[6]), .E
       (n_175), .Q (\fifo_ram[11] [6]));
  EDFFHQX1 \fifo_ram_reg[10][1] (.CK (clk), .D (data_in[1]), .E
       (n_183), .Q (\fifo_ram[10] [1]));
  NAND4XL g5395__4733(.A (n_70), .B (n_125), .C (n_79), .D (n_87), .Y
       (n_174));
  AOI221X1 g5466__6161(.A0 (\fifo_ram[6] [4]), .A1 (n_171), .B0
       (\fifo_ram[5] [4]), .B1 (n_170), .C0 (n_117), .Y (n_173));
  AOI221X1 g5467__9315(.A0 (\fifo_ram[6] [1]), .A1 (n_171), .B0
       (\fifo_ram[5] [1]), .B1 (n_170), .C0 (n_135), .Y (n_172));
  AOI221X1 g5468__9945(.A0 (\fifo_ram[2] [5]), .A1 (n_166), .B0
       (\fifo_ram[1] [5]), .B1 (n_165), .C0 (n_94), .Y (n_169));
  AOI221X1 g5469__2883(.A0 (\fifo_ram[6] [6]), .A1 (n_171), .B0
       (\fifo_ram[5] [6]), .B1 (n_170), .C0 (n_103), .Y (n_168));
  AOI221X1 g5470__2346(.A0 (\fifo_ram[2] [0]), .A1 (n_166), .B0
       (\fifo_ram[1] [0]), .B1 (n_165), .C0 (n_98), .Y (n_167));
  AOI221X1 g5471__1666(.A0 (\fifo_ram[2] [2]), .A1 (n_166), .B0
       (\fifo_ram[1] [2]), .B1 (n_165), .C0 (n_101), .Y (n_164));
  EDFFHQX1 \fifo_ram_reg[2][3] (.CK (clk), .D (data_in[3]), .E (n_154),
       .Q (\fifo_ram[2] [3]));
  EDFFHQX1 \fifo_ram_reg[5][5] (.CK (clk), .D (data_in[5]), .E (n_160),
       .Q (\fifo_ram[5] [5]));
  EDFFHQX1 \fifo_ram_reg[6][6] (.CK (clk), .D (data_in[6]), .E (n_153),
       .Q (\fifo_ram[6] [6]));
  NAND4XL g5388__7410(.A (n_76), .B (n_56), .C (n_58), .D (n_114), .Y
       (n_163));
  NAND4XL g5389__6417(.A (n_75), .B (n_96), .C (n_57), .D (n_80), .Y
       (n_162));
  NAND4XL g5390__5477(.A (n_66), .B (n_59), .C (n_60), .D (n_99), .Y
       (n_161));
  EDFFHQX1 \fifo_ram_reg[5][1] (.CK (clk), .D (data_in[1]), .E (n_160),
       .Q (\fifo_ram[5] [1]));
  EDFFHQX1 \fifo_ram_reg[1][7] (.CK (clk), .D (data_in[7]), .E (n_151),
       .Q (\fifo_ram[1] [7]));
  NAND4XL g5391__2398(.A (n_88), .B (n_63), .C (n_64), .D (n_126), .Y
       (n_159));
  NAND4XL g5392__5107(.A (n_62), .B (n_106), .C (n_65), .D (n_61), .Y
       (n_158));
  OAI211XL g5325__6260(.A0 (n_83), .A1 (n_52), .B0 (n_51), .C0 (n_108),
       .Y (n_157));
  NAND4XL g5393__4319(.A (n_67), .B (n_82), .C (n_81), .D (n_113), .Y
       (n_156));
  NAND4XL g5394__8428(.A (n_69), .B (n_71), .C (n_72), .D (n_120), .Y
       (n_155));
  EDFFHQX1 \fifo_ram_reg[4][5] (.CK (clk), .D (data_in[5]), .E (n_152),
       .Q (\fifo_ram[4] [5]));
  EDFFHQX1 \fifo_ram_reg[2][7] (.CK (clk), .D (data_in[7]), .E (n_154),
       .Q (\fifo_ram[2] [7]));
  EDFFHQX1 \fifo_ram_reg[6][5] (.CK (clk), .D (data_in[5]), .E (n_153),
       .Q (\fifo_ram[6] [5]));
  EDFFHQX1 \fifo_ram_reg[6][1] (.CK (clk), .D (data_in[1]), .E (n_153),
       .Q (\fifo_ram[6] [1]));
  EDFFHQX1 \fifo_ram_reg[4][1] (.CK (clk), .D (data_in[1]), .E (n_152),
       .Q (\fifo_ram[4] [1]));
  EDFFHQX1 \fifo_ram_reg[1][2] (.CK (clk), .D (data_in[2]), .E (n_151),
       .Q (\fifo_ram[1] [2]));
  EDFFHQX1 \fifo_ram_reg[0][0] (.CK (clk), .D (data_in[0]), .E (n_150),
       .Q (\fifo_ram[0] [0]));
  EDFFHQX1 \fifo_ram_reg[0][1] (.CK (clk), .D (data_in[1]), .E (n_150),
       .Q (\fifo_ram[0] [1]));
  EDFFHQX1 \fifo_ram_reg[0][2] (.CK (clk), .D (data_in[2]), .E (n_150),
       .Q (\fifo_ram[0] [2]));
  EDFFHQX1 \fifo_ram_reg[0][3] (.CK (clk), .D (data_in[3]), .E (n_150),
       .Q (\fifo_ram[0] [3]));
  EDFFHQX1 \fifo_ram_reg[0][4] (.CK (clk), .D (data_in[4]), .E (n_150),
       .Q (\fifo_ram[0] [4]));
  EDFFHQX1 \fifo_ram_reg[0][5] (.CK (clk), .D (data_in[5]), .E (n_150),
       .Q (\fifo_ram[0] [5]));
  EDFFHQX1 \fifo_ram_reg[0][7] (.CK (clk), .D (data_in[7]), .E (n_150),
       .Q (\fifo_ram[0] [7]));
  EDFFHQX1 \fifo_ram_reg[0][6] (.CK (clk), .D (data_in[6]), .E (n_150),
       .Q (\fifo_ram[0] [6]));
  EDFFHQX1 \fifo_ram_reg[1][0] (.CK (clk), .D (data_in[0]), .E (n_151),
       .Q (\fifo_ram[1] [0]));
  EDFFHQX1 \fifo_ram_reg[1][1] (.CK (clk), .D (data_in[1]), .E (n_151),
       .Q (\fifo_ram[1] [1]));
  EDFFHQX1 \fifo_ram_reg[1][3] (.CK (clk), .D (data_in[3]), .E (n_151),
       .Q (\fifo_ram[1] [3]));
  EDFFHQX1 \fifo_ram_reg[1][4] (.CK (clk), .D (data_in[4]), .E (n_151),
       .Q (\fifo_ram[1] [4]));
  EDFFHQX1 \fifo_ram_reg[3][1] (.CK (clk), .D (data_in[1]), .E (n_149),
       .Q (\fifo_ram[3] [1]));
  EDFFHQX1 \fifo_ram_reg[3][2] (.CK (clk), .D (data_in[2]), .E (n_149),
       .Q (\fifo_ram[3] [2]));
  EDFFHQX1 \fifo_ram_reg[3][3] (.CK (clk), .D (data_in[3]), .E (n_149),
       .Q (\fifo_ram[3] [3]));
  EDFFHQX1 \fifo_ram_reg[3][4] (.CK (clk), .D (data_in[4]), .E (n_149),
       .Q (\fifo_ram[3] [4]));
  EDFFHQX1 \fifo_ram_reg[3][5] (.CK (clk), .D (data_in[5]), .E (n_149),
       .Q (\fifo_ram[3] [5]));
  EDFFHQX1 \fifo_ram_reg[3][6] (.CK (clk), .D (data_in[6]), .E (n_149),
       .Q (\fifo_ram[3] [6]));
  EDFFHQX1 \fifo_ram_reg[3][7] (.CK (clk), .D (data_in[7]), .E (n_149),
       .Q (\fifo_ram[3] [7]));
  EDFFHQX1 \fifo_ram_reg[4][0] (.CK (clk), .D (data_in[0]), .E (n_152),
       .Q (\fifo_ram[4] [0]));
  EDFFHQX1 \fifo_ram_reg[4][2] (.CK (clk), .D (data_in[2]), .E (n_152),
       .Q (\fifo_ram[4] [2]));
  EDFFHQX1 \fifo_ram_reg[4][3] (.CK (clk), .D (data_in[3]), .E (n_152),
       .Q (\fifo_ram[4] [3]));
  EDFFHQX1 \fifo_ram_reg[4][4] (.CK (clk), .D (data_in[4]), .E (n_152),
       .Q (\fifo_ram[4] [4]));
  EDFFHQX1 \fifo_ram_reg[4][6] (.CK (clk), .D (data_in[6]), .E (n_152),
       .Q (\fifo_ram[4] [6]));
  EDFFHQX1 \fifo_ram_reg[4][7] (.CK (clk), .D (data_in[7]), .E (n_152),
       .Q (\fifo_ram[4] [7]));
  EDFFHQX1 \fifo_ram_reg[5][0] (.CK (clk), .D (data_in[0]), .E (n_160),
       .Q (\fifo_ram[5] [0]));
  EDFFHQX1 \fifo_ram_reg[5][2] (.CK (clk), .D (data_in[2]), .E (n_160),
       .Q (\fifo_ram[5] [2]));
  EDFFHQX1 \fifo_ram_reg[5][3] (.CK (clk), .D (data_in[3]), .E (n_160),
       .Q (\fifo_ram[5] [3]));
  EDFFHQX1 \fifo_ram_reg[5][4] (.CK (clk), .D (data_in[4]), .E (n_160),
       .Q (\fifo_ram[5] [4]));
  EDFFHQX1 \fifo_ram_reg[5][6] (.CK (clk), .D (data_in[6]), .E (n_160),
       .Q (\fifo_ram[5] [6]));
  EDFFHQX1 \fifo_ram_reg[5][7] (.CK (clk), .D (data_in[7]), .E (n_160),
       .Q (\fifo_ram[5] [7]));
  EDFFHQX1 \fifo_ram_reg[6][0] (.CK (clk), .D (data_in[0]), .E (n_153),
       .Q (\fifo_ram[6] [0]));
  EDFFHQX1 \fifo_ram_reg[6][3] (.CK (clk), .D (data_in[3]), .E (n_153),
       .Q (\fifo_ram[6] [3]));
  EDFFHQX1 \fifo_ram_reg[6][4] (.CK (clk), .D (data_in[4]), .E (n_153),
       .Q (\fifo_ram[6] [4]));
  EDFFHQX1 \fifo_ram_reg[15][5] (.CK (clk), .D (data_in[5]), .E
       (n_148), .Q (\fifo_ram[15] [5]));
  EDFFHQX1 \fifo_ram_reg[6][7] (.CK (clk), .D (data_in[7]), .E (n_153),
       .Q (\fifo_ram[6] [7]));
  EDFFHQX1 \fifo_ram_reg[6][2] (.CK (clk), .D (data_in[2]), .E (n_153),
       .Q (\fifo_ram[6] [2]));
  EDFFHQX1 \fifo_ram_reg[3][0] (.CK (clk), .D (data_in[0]), .E (n_149),
       .Q (\fifo_ram[3] [0]));
  EDFFHQX1 \fifo_ram_reg[2][6] (.CK (clk), .D (data_in[6]), .E (n_154),
       .Q (\fifo_ram[2] [6]));
  EDFFHQX1 \fifo_ram_reg[2][5] (.CK (clk), .D (data_in[5]), .E (n_154),
       .Q (\fifo_ram[2] [5]));
  EDFFHQX1 \fifo_ram_reg[2][4] (.CK (clk), .D (data_in[4]), .E (n_154),
       .Q (\fifo_ram[2] [4]));
  EDFFHQX1 \fifo_ram_reg[2][2] (.CK (clk), .D (data_in[2]), .E (n_154),
       .Q (\fifo_ram[2] [2]));
  EDFFHQX1 \fifo_ram_reg[2][1] (.CK (clk), .D (data_in[1]), .E (n_154),
       .Q (\fifo_ram[2] [1]));
  EDFFHQX1 \fifo_ram_reg[2][0] (.CK (clk), .D (data_in[0]), .E (n_154),
       .Q (\fifo_ram[2] [0]));
  EDFFHQX1 \fifo_ram_reg[1][5] (.CK (clk), .D (data_in[5]), .E (n_151),
       .Q (\fifo_ram[1] [5]));
  EDFFHQX1 \fifo_ram_reg[1][6] (.CK (clk), .D (data_in[6]), .E (n_151),
       .Q (\fifo_ram[1] [6]));
  EDFFHQX1 \fifo_ram_reg[15][0] (.CK (clk), .D (data_in[0]), .E
       (n_148), .Q (\fifo_ram[15] [0]));
  EDFFHQX1 \fifo_ram_reg[15][1] (.CK (clk), .D (data_in[1]), .E
       (n_148), .Q (\fifo_ram[15] [1]));
  EDFFHQX1 \fifo_ram_reg[15][2] (.CK (clk), .D (data_in[2]), .E
       (n_148), .Q (\fifo_ram[15] [2]));
  EDFFHQX1 \fifo_ram_reg[15][3] (.CK (clk), .D (data_in[3]), .E
       (n_148), .Q (\fifo_ram[15] [3]));
  EDFFHQX1 \fifo_ram_reg[15][4] (.CK (clk), .D (data_in[4]), .E
       (n_148), .Q (\fifo_ram[15] [4]));
  EDFFHQX1 \fifo_ram_reg[15][6] (.CK (clk), .D (data_in[6]), .E
       (n_148), .Q (\fifo_ram[15] [6]));
  EDFFHQX1 \fifo_ram_reg[15][7] (.CK (clk), .D (data_in[7]), .E
       (n_148), .Q (\fifo_ram[15] [7]));
  AOI221X1 g5464__5526(.A0 (\fifo_ram[2] [7]), .A1 (n_166), .B0
       (\fifo_ram[1] [7]), .B1 (n_165), .C0 (n_121), .Y (n_147));
  AOI221X1 g5465__6783(.A0 (\fifo_ram[6] [3]), .A1 (n_171), .B0
       (\fifo_ram[5] [3]), .B1 (n_170), .C0 (n_122), .Y (n_146));
  INVXL g5319(.A (n_142), .Y (n_145));
  NAND2XL g5316__3680(.A (count[4]), .B (n_143), .Y (n_144));
  AOI222XL g5324__1617(.A0 (n_10), .A1 (n_139), .B0 (n_138), .B1
       (n_110), .C0 (n_137), .C1 (count[2]), .Y (n_142));
  EDFFHQX1 \fifo_ram_reg[7][6] (.CK (clk), .D (data_in[6]), .E (n_141),
       .Q (\fifo_ram[7] [6]));
  EDFFHQX1 \fifo_ram_reg[7][1] (.CK (clk), .D (data_in[1]), .E (n_141),
       .Q (\fifo_ram[7] [1]));
  EDFFHQX1 \fifo_ram_reg[7][5] (.CK (clk), .D (data_in[5]), .E (n_141),
       .Q (\fifo_ram[7] [5]));
  AOI221X1 g5396__2802(.A0 (n_43), .A1 (n_139), .B0 (n_138), .B1
       (n_32), .C0 (n_137), .Y (n_140));
  EDFFHQX1 \fifo_ram_reg[7][3] (.CK (clk), .D (data_in[3]), .E (n_141),
       .Q (\fifo_ram[7] [3]));
  EDFFHQX1 \fifo_ram_reg[7][2] (.CK (clk), .D (data_in[2]), .E (n_141),
       .Q (\fifo_ram[7] [2]));
  EDFFHQX1 \fifo_ram_reg[7][0] (.CK (clk), .D (data_in[0]), .E (n_141),
       .Q (\fifo_ram[7] [0]));
  EDFFHQX1 \fifo_ram_reg[7][4] (.CK (clk), .D (data_in[4]), .E (n_141),
       .Q (\fifo_ram[7] [4]));
  EDFFHQX1 \fifo_ram_reg[7][7] (.CK (clk), .D (data_in[7]), .E (n_141),
       .Q (\fifo_ram[7] [7]));
  AOI22XL g5512__1705(.A0 (n_128), .A1 (\fifo_ram[0] [5]), .B0 (n_171),
       .B1 (\fifo_ram[6] [5]), .Y (n_136));
  AO22X1 g5511__5122(.A0 (\fifo_ram[4] [1]), .A1 (n_127), .B0
       (\fifo_ram[3] [1]), .B1 (n_131), .Y (n_135));
  AOI22XL g5478__8246(.A0 (n_171), .A1 (\fifo_ram[6] [2]), .B0 (n_170),
       .B1 (\fifo_ram[5] [2]), .Y (n_134));
  AOI22XL g5483__7098(.A0 (n_165), .A1 (\fifo_ram[1] [6]), .B0 (n_130),
       .B1 (data_out[6]), .Y (n_133));
  AOI22XL g5484__6131(.A0 (n_131), .A1 (\fifo_ram[3] [3]), .B0 (n_130),
       .B1 (data_out[3]), .Y (n_132));
  AOI22XL g5485__1881(.A0 (n_128), .A1 (\fifo_ram[0] [3]), .B0 (n_127),
       .B1 (\fifo_ram[4] [3]), .Y (n_129));
  AOI22XL g5486__5115(.A0 (n_124), .A1 (\fifo_ram[8] [5]), .B0 (n_123),
       .B1 (\fifo_ram[7] [5]), .Y (n_126));
  AOI22XL g5487__7482(.A0 (n_124), .A1 (\fifo_ram[8] [0]), .B0 (n_123),
       .B1 (\fifo_ram[7] [0]), .Y (n_125));
  AO22X1 g5488__4733(.A0 (\fifo_ram[2] [3]), .A1 (n_166), .B0
       (\fifo_ram[1] [3]), .B1 (n_165), .Y (n_122));
  AO22X1 g5493__6161(.A0 (\fifo_ram[4] [7]), .A1 (n_127), .B0
       (\fifo_ram[3] [7]), .B1 (n_131), .Y (n_121));
  AOI22XL g5496__9315(.A0 (n_124), .A1 (\fifo_ram[8] [3]), .B0 (n_123),
       .B1 (\fifo_ram[7] [3]), .Y (n_120));
  AOI22XL g5498__9945(.A0 (n_131), .A1 (\fifo_ram[3] [4]), .B0 (n_130),
       .B1 (data_out[4]), .Y (n_119));
  AOI22XL g5499__2883(.A0 (n_128), .A1 (\fifo_ram[0] [4]), .B0 (n_127),
       .B1 (\fifo_ram[4] [4]), .Y (n_118));
  AO22X1 g5501__2346(.A0 (\fifo_ram[2] [4]), .A1 (n_166), .B0
       (\fifo_ram[1] [4]), .B1 (n_165), .Y (n_117));
  AOI22XL g5502__1666(.A0 (n_128), .A1 (\fifo_ram[0] [1]), .B0 (n_130),
       .B1 (data_out[1]), .Y (n_116));
  AOI22XL g5503__7410(.A0 (n_128), .A1 (\fifo_ram[0] [0]), .B0 (n_130),
       .B1 (data_out[0]), .Y (n_115));
  AOI22XL g5507__6417(.A0 (n_124), .A1 (\fifo_ram[8] [7]), .B0 (n_123),
       .B1 (\fifo_ram[7] [7]), .Y (n_114));
  AOI22XL g5509__5477(.A0 (n_124), .A1 (\fifo_ram[8] [4]), .B0 (n_123),
       .B1 (\fifo_ram[7] [4]), .Y (n_113));
  AOI31X1 g5397__2398(.A0 (count[2]), .A1 (n_111), .A2 (n_110), .B0
       (n_93), .Y (n_112));
  CLKAND2X2 g5558__5107(.A (n_92), .B (n_109), .Y (n_178));
  CLKAND2X2 g5560__6260(.A (n_89), .B (n_109), .Y (n_177));
  NAND2XL g5398__4319(.A (count[1]), .B (n_137), .Y (n_108));
  AOI22XL g5515__8428(.A0 (n_170), .A1 (\fifo_ram[5] [7]), .B0 (n_130),
       .B1 (data_out[7]), .Y (n_107));
  AOI22XL g5517__5526(.A0 (n_124), .A1 (\fifo_ram[8] [1]), .B0 (n_123),
       .B1 (\fifo_ram[7] [1]), .Y (n_106));
  AOI22XL g5520__6783(.A0 (n_171), .A1 (\fifo_ram[6] [0]), .B0 (n_170),
       .B1 (\fifo_ram[5] [0]), .Y (n_105));
  AOI22XL g5522__3680(.A0 (n_166), .A1 (\fifo_ram[2] [6]), .B0 (n_131),
       .B1 (\fifo_ram[3] [6]), .Y (n_104));
  AO22X1 g5523__1617(.A0 (\fifo_ram[0] [6]), .A1 (n_128), .B0
       (\fifo_ram[4] [6]), .B1 (n_127), .Y (n_103));
  AOI22XL g5524__2802(.A0 (n_128), .A1 (\fifo_ram[0] [2]), .B0 (n_130),
       .B1 (data_out[2]), .Y (n_102));
  AO22X1 g5527__1705(.A0 (\fifo_ram[4] [2]), .A1 (n_127), .B0
       (\fifo_ram[3] [2]), .B1 (n_131), .Y (n_101));
  AOI22XL g5528__5122(.A0 (n_166), .A1 (\fifo_ram[2] [1]), .B0 (n_165),
       .B1 (\fifo_ram[1] [1]), .Y (n_100));
  AOI22XL g5529__8246(.A0 (n_124), .A1 (\fifo_ram[8] [6]), .B0 (n_123),
       .B1 (\fifo_ram[7] [6]), .Y (n_99));
  AO22X1 g5530__7098(.A0 (\fifo_ram[4] [0]), .A1 (n_127), .B0
       (\fifo_ram[3] [0]), .B1 (n_131), .Y (n_98));
  AOI22XL g5531__6131(.A0 (n_128), .A1 (\fifo_ram[0] [7]), .B0 (n_171),
       .B1 (\fifo_ram[6] [7]), .Y (n_97));
  AOI22XL g5533__1881(.A0 (n_124), .A1 (\fifo_ram[8] [2]), .B0 (n_123),
       .B1 (\fifo_ram[7] [2]), .Y (n_96));
  AOI22XL g5536__5115(.A0 (n_170), .A1 (\fifo_ram[5] [5]), .B0 (n_130),
       .B1 (data_out[5]), .Y (n_95));
  AO22X1 g5513__7482(.A0 (\fifo_ram[4] [5]), .A1 (n_127), .B0
       (\fifo_ram[3] [5]), .B1 (n_131), .Y (n_94));
  AOI31X1 g5440__4733(.A0 (count[2]), .A1 (count[3]), .A2 (n_110), .B0
       (n_93), .Y (n_143));
  CLKAND2X2 g5551__6161(.A (n_90), .B (n_91), .Y (n_182));
  CLKAND2X2 g5552__9315(.A (n_92), .B (n_91), .Y (n_181));
  CLKAND2X2 g5553__9945(.A (n_55), .B (n_91), .Y (n_175));
  CLKAND2X2 g5554__2883(.A (n_90), .B (n_109), .Y (n_179));
  CLKAND2X2 g5556__2346(.A (n_89), .B (n_91), .Y (n_183));
  AOI22XL g5500__1666(.A0 (n_86), .A1 (\fifo_ram[10] [5]), .B0 (n_85),
       .B1 (\fifo_ram[9] [5]), .Y (n_88));
  AOI22XL g5497__7410(.A0 (n_86), .A1 (\fifo_ram[10] [0]), .B0 (n_85),
       .B1 (\fifo_ram[9] [0]), .Y (n_87));
  AOI22XL g5477__5477(.A0 (n_74), .A1 (\fifo_ram[12] [4]), .B0 (n_73),
       .B1 (\fifo_ram[11] [4]), .Y (n_82));
  AOI22XL g5479__2398(.A0 (n_78), .A1 (\fifo_ram[14] [4]), .B0 (n_77),
       .B1 (\fifo_ram[13] [4]), .Y (n_81));
  AOI22XL g5481__5107(.A0 (n_86), .A1 (\fifo_ram[10] [2]), .B0 (n_85),
       .B1 (\fifo_ram[9] [2]), .Y (n_80));
  AOI22XL g5482__6260(.A0 (n_78), .A1 (\fifo_ram[14] [0]), .B0 (n_77),
       .B1 (\fifo_ram[13] [0]), .Y (n_79));
  AOI22XL g5495__4319(.A0 (n_86), .A1 (\fifo_ram[10] [7]), .B0 (n_85),
       .B1 (\fifo_ram[9] [7]), .Y (n_76));
  AOI22XL g5489__8428(.A0 (n_74), .A1 (\fifo_ram[12] [2]), .B0 (n_73),
       .B1 (\fifo_ram[11] [2]), .Y (n_75));
  AOI22XL g5490__5526(.A0 (n_78), .A1 (\fifo_ram[14] [3]), .B0 (n_77),
       .B1 (\fifo_ram[13] [3]), .Y (n_72));
  AOI22XL g5491__6783(.A0 (n_86), .A1 (\fifo_ram[10] [3]), .B0 (n_85),
       .B1 (\fifo_ram[9] [3]), .Y (n_71));
  AOI22XL g5492__3680(.A0 (n_74), .A1 (\fifo_ram[12] [0]), .B0 (n_73),
       .B1 (\fifo_ram[11] [0]), .Y (n_70));
  AOI22XL g5494__1617(.A0 (n_74), .A1 (\fifo_ram[12] [3]), .B0 (n_73),
       .B1 (\fifo_ram[11] [3]), .Y (n_69));
  AND2X1 g5591__2802(.A (n_45), .B (n_44), .Y (n_148));
  CLKAND2X2 g5557__1705(.A (n_89), .B (n_68), .Y (n_154));
  CLKAND2X2 g5559__5122(.A (n_92), .B (n_68), .Y (n_151));
  AOI22XL g5508__8246(.A0 (n_86), .A1 (\fifo_ram[10] [4]), .B0 (n_85),
       .B1 (\fifo_ram[9] [4]), .Y (n_67));
  AOI22XL g5510__7098(.A0 (n_86), .A1 (\fifo_ram[10] [6]), .B0 (n_85),
       .B1 (\fifo_ram[9] [6]), .Y (n_66));
  AOI22XL g5514__6131(.A0 (n_78), .A1 (\fifo_ram[14] [1]), .B0 (n_77),
       .B1 (\fifo_ram[13] [1]), .Y (n_65));
  AOI22XL g5516__1881(.A0 (n_78), .A1 (\fifo_ram[14] [5]), .B0 (n_77),
       .B1 (\fifo_ram[13] [5]), .Y (n_64));
  AOI22XL g5518__5115(.A0 (n_74), .A1 (\fifo_ram[12] [5]), .B0 (n_73),
       .B1 (\fifo_ram[11] [5]), .Y (n_63));
  AOI22XL g5519__7482(.A0 (n_74), .A1 (\fifo_ram[12] [1]), .B0 (n_73),
       .B1 (\fifo_ram[11] [1]), .Y (n_62));
  AOI22XL g5521__4733(.A0 (n_86), .A1 (\fifo_ram[10] [1]), .B0 (n_85),
       .B1 (\fifo_ram[9] [1]), .Y (n_61));
  AOI22XL g5525__6161(.A0 (n_78), .A1 (\fifo_ram[14] [6]), .B0 (n_77),
       .B1 (\fifo_ram[13] [6]), .Y (n_60));
  AOI22XL g5526__9315(.A0 (n_74), .A1 (\fifo_ram[12] [6]), .B0 (n_73),
       .B1 (\fifo_ram[11] [6]), .Y (n_59));
  AOI22XL g5534__9945(.A0 (n_78), .A1 (\fifo_ram[14] [7]), .B0 (n_77),
       .B1 (\fifo_ram[13] [7]), .Y (n_58));
  AOI22XL g5532__2883(.A0 (n_78), .A1 (\fifo_ram[14] [2]), .B0 (n_77),
       .B1 (\fifo_ram[13] [2]), .Y (n_57));
  AOI22XL g5535__2346(.A0 (n_74), .A1 (\fifo_ram[12] [7]), .B0 (n_73),
       .B1 (\fifo_ram[11] [7]), .Y (n_56));
  AND2X1 g5550__1666(.A (n_90), .B (n_54), .Y (n_152));
  CLKAND2X2 g5549__7410(.A (n_90), .B (n_68), .Y (n_150));
  CLKAND2X2 g5548__6417(.A (n_55), .B (n_68), .Y (n_149));
  AND2X1 g5555__5477(.A (n_89), .B (n_54), .Y (n_153));
  AND2X1 g5547__2398(.A (n_92), .B (n_54), .Y (n_160));
  NOR2XL g5561__5107(.A (n_39), .B (n_53), .Y (n_109));
  NOR2XL g5564__6260(.A (w_ptr[2]), .B (n_53), .Y (n_91));
  NAND2XL g5476__4319(.A (n_33), .B (n_52), .Y (n_137));
  DFFRHQX1 \w_ptr_reg[0] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (w_ptr[0]));
  OAI21XL g5480__8428(.A0 (n_5), .A1 (n_9), .B0 (n_139), .Y (n_51));
  AND2X1 g5562__5526(.A (w_ptr[2]), .B (n_208), .Y (n_54));
  NOR2BX1 g5563__6783(.AN (n_208), .B (w_ptr[2]), .Y (n_68));
  AND2X1 g5570__3680(.A (n_42), .B (n_49), .Y (n_127));
  AND2X1 g5571__1617(.A (n_47), .B (n_49), .Y (n_166));
  AND2X1 g5572__2802(.A (n_41), .B (n_49), .Y (n_171));
  AND2X1 g5567__1705(.A (n_48), .B (n_46), .Y (n_165));
  AND2X1 g5566__5122(.A (n_48), .B (n_49), .Y (n_128));
  AND2X1 g5586__8246(.A (n_47), .B (n_46), .Y (n_131));
  AND2X1 g5575__7098(.A (n_45), .B (n_208), .Y (n_141));
  INVXL g5596(.A (n_53), .Y (n_44));
  NOR3X1 g5504__6131(.A (count[3]), .B (n_43), .C (n_19), .Y (n_93));
  DFFRHQX1 \w_ptr_reg[3] (.RN (rst_n), .CK (clk), .D (n_26), .Q
       (w_ptr[3]));
  DFFRHQX1 \w_ptr_reg[1] (.RN (rst_n), .CK (clk), .D (n_21), .Q
       (w_ptr[1]));
  DFFRHQX1 \r_ptr_reg[1] (.RN (rst_n), .CK (clk), .D (n_25), .Q
       (r_ptr[1]));
  DFFRHQX1 \r_ptr_reg[3] (.RN (rst_n), .CK (clk), .D (n_206), .Q
       (r_ptr[3]));
  AND2X1 g5588__1881(.A (n_42), .B (n_46), .Y (n_170));
  AND2X1 g5589__5115(.A (n_41), .B (n_46), .Y (n_123));
  OAI32X1 g5583__7482(.A0 (n_8), .A1 (n_37), .A2 (n_45), .B0 (n_39),
       .B1 (n_36), .Y (n_40));
  MXI2XL g5577__4733(.A (n_37), .B (n_36), .S0 (w_ptr[0]), .Y (n_38));
  NOR2XL g5569__6161(.A (n_30), .B (n_35), .Y (n_190));
  NOR2XL g5574__9315(.A (n_27), .B (n_35), .Y (n_73));
  NOR2BX1 g5573__9945(.AN (n_48), .B (n_29), .Y (n_124));
  NOR2BX1 g5565__2883(.AN (n_48), .B (n_35), .Y (n_85));
  NOR2XL g5568__2346(.A (n_28), .B (n_35), .Y (n_77));
  NAND2XL g5505__1666(.A (n_31), .B (n_32), .Y (n_52));
  NAND3X1 g5598__7410(.A (rst_n), .B (w_ptr[3]), .C (n_36), .Y (n_53));
  NOR2BX1 g5506__6417(.AN (n_32), .B (n_31), .Y (n_110));
  NOR2XL g5590__5477(.A (n_30), .B (n_29), .Y (n_78));
  NOR2XL g5587__2398(.A (n_28), .B (n_29), .Y (n_74));
  NOR2XL g5585__5107(.A (n_27), .B (n_29), .Y (n_86));
  MX2X1 g5579__6260(.A (n_11), .B (w_ptr[3]), .S0 (n_37), .Y (n_26));
  MX3XL g5578__4319(.A (r_ptr[0]), .B (n_18), .C (r_ptr[1]), .S0
       (r_ptr[1]), .S1 (n_130), .Y (n_25));
  MXI2XL g5576__8428(.A (n_130), .B (n_20), .S0 (r_ptr[0]), .Y (n_24));
  MXI2XL g5581__6783(.A (n_12), .B (n_4), .S0 (n_130), .Y (n_22));
  MX2X1 g5582__3680(.A (n_7), .B (w_ptr[1]), .S0 (n_37), .Y (n_21));
  MXI2XL g5584__1617(.A (n_20), .B (n_130), .S0 (n_37), .Y (n_33));
  CLKINVX1 g5538(.A (n_19), .Y (n_139));
  NOR3X1 g5599__1705(.A (r_ptr[3]), .B (n_18), .C (n_130), .Y (n_46));
  NOR3X1 g5595__5122(.A (r_ptr[0]), .B (r_ptr[3]), .C (n_130), .Y
       (n_49));
  NAND2XL g5593__8246(.A (n_37), .B (n_20), .Y (n_19));
  NOR2XL g5592__7098(.A (n_37), .B (n_20), .Y (n_32));
  NAND3X1 g5594__6131(.A (r_ptr[3]), .B (r_ptr[0]), .C (n_20), .Y
       (n_35));
  NAND3X1 g5600__1881(.A (r_ptr[3]), .B (n_18), .C (n_20), .Y (n_29));
  CLKINVX1 g5603(.A (n_37), .Y (n_36));
  NAND2BX2 g5605__5115(.AN (n_16), .B (wr_en), .Y (n_37));
  CLKINVX2 g5601(.A (n_20), .Y (n_130));
  NOR2BX2 g5602__7482(.AN (rd_en), .B (empty), .Y (n_20));
  BUFX2 g5608(.A (n_16), .Y (full));
  AOI221X1 g5612__6161(.A0 (r_ptr[2]), .A1 (n_18), .B0 (r_ptr[0]), .B1
       (n_47), .C0 (n_42), .Y (n_12));
  XOR2XL g5604__9315(.A (w_ptr[3]), .B (n_45), .Y (n_11));
  NOR3BX1 g5609__9945(.AN (count[4]), .B (count[3]), .C (n_43), .Y
       (n_16));
  OAI21X1 g5611__2346(.A0 (n_138), .A1 (n_9), .B0 (n_43), .Y (n_10));
  NOR2XL g5613__1666(.A (w_ptr[2]), .B (n_55), .Y (n_8));
  OR2XL g5615__7410(.A (n_92), .B (n_89), .Y (n_7));
  NAND2X2 g5614__5477(.A (n_138), .B (n_9), .Y (n_43));
  CLKINVX1 g5625(.A (n_42), .Y (n_28));
  CLKINVX1 g5626(.A (n_27), .Y (n_47));
  NOR2XL g5617__2398(.A (n_39), .B (n_3), .Y (n_45));
  INVXL g5618(.A (n_31), .Y (n_5));
  NOR2XL g5629__5107(.A (r_ptr[1]), .B (n_4), .Y (n_42));
  CLKINVX1 g5627(.A (n_30), .Y (n_41));
  NAND2XL g5632__6260(.A (r_ptr[1]), .B (n_4), .Y (n_27));
  CLKINVX1 g5619(.A (n_3), .Y (n_55));
  NOR2X2 g5628__8428(.A (count[0]), .B (count[1]), .Y (n_9));
  NOR2XL g5622__5526(.A (r_ptr[1]), .B (r_ptr[2]), .Y (n_48));
  NOR2BX1 g5630__6783(.AN (w_ptr[1]), .B (w_ptr[0]), .Y (n_89));
  NAND2XL g5624__3680(.A (w_ptr[0]), .B (w_ptr[1]), .Y (n_3));
  NAND2XL g5621__1617(.A (count[0]), .B (count[1]), .Y (n_31));
  NOR2XL g5623__2802(.A (w_ptr[0]), .B (w_ptr[1]), .Y (n_90));
  NAND2XL g5633__1705(.A (r_ptr[1]), .B (r_ptr[2]), .Y (n_30));
  NOR2BX1 g5631__5122(.AN (w_ptr[0]), .B (w_ptr[1]), .Y (n_92));
  XNOR2X1 g2(.A (n_205), .B (r_ptr[3]), .Y (n_206));
  OR3XL g3(.A (n_18), .B (n_30), .C (n_130), .Y (n_205));
  DFFRX2 \count_reg[0] (.RN (rst_n), .CK (clk), .D (n_207), .Q
       (count[0]), .QN (n_83));
  DFFRX1 \count_reg[2] (.RN (rst_n), .CK (clk), .D (n_145), .Q
       (count[2]), .QN (n_138));
  DFFRX1 \r_ptr_reg[0] (.RN (rst_n), .CK (clk), .D (n_24), .Q
       (r_ptr[0]), .QN (n_18));
  DFFRX1 \count_reg[3] (.RN (rst_n), .CK (clk), .D (n_180), .Q
       (count[3]), .QN (n_111));
  DFFRX1 \w_ptr_reg[2] (.RN (rst_n), .CK (clk), .D (n_40), .Q
       (w_ptr[2]), .QN (n_39));
  DFFRX1 \r_ptr_reg[2] (.RN (rst_n), .CK (clk), .D (n_22), .Q
       (r_ptr[2]), .QN (n_4));
  MXI2XL g5803(.A (n_83), .B (count[0]), .S0 (n_33), .Y (n_207));
  NOR3BX1 g5804(.AN (rst_n), .B (w_ptr[3]), .C (n_37), .Y (n_208));
  NOR3X2 g5805(.A (count[3]), .B (count[4]), .C (n_43), .Y (empty));
endmodule

